# Generated by Django 4.1.3 on 2022-11-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_recepcion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
    ]
